version: "3"

services:
  web:
    container_name: phpengine_app
    image: satishkalepu/amazon-apache-php82
    ports:
      - "8888:80"
    volumes:
      - .:/var/www/html/

  mongo:
    container_name: phpengine_db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: stage
      MONGO_INITDB_ROOT_PASSWORD: stage 
    ports:
      - "27017:27017"

  redis:
    container_name: phpengine_redis
<<<<<<< HEAD
    image: redis:latest
    ports:
      - "6379:6379"
=======
    image: redis
    ports:
      - "6379:6379"
>>>>>>> c2b5a9372a935a8e859be832fffbd76f4f46f7c8
